#include<stdio.h>
int main(){
    int a[5][5],n,i,j,k,b,c;
    for(i=0;i<5;i++){
        for(j=0;j<5;j++){
            scanf("%d",&a[i][j]);
        }
    }
    for(k=1;k<=25;k++){
        scanf("%d",&n);
        for(i=0;i<5;i++){
            for(j=0;j<5;j++){
                if(a[i][j]==n){
                    a[i][j]=0;
                }
            }
        }
        b=0;
        for(i=0;i<5;i++){
            c=0;
            for(j=0;j<5;j++){
                if(a[i][j]==0){
                    c=c+1;
                }
                else{
                    break;
                }
            }
            if(c==5){
                b=b+1;    
            }
        }
        for(i=0;i<5;i++){
            c=0;
            for(j=0;j<5;j++){
                if(a[j][i]==0){
                    c=c+1;
                }
                else{
                    break;
                }
            }
            if(c==5){
                b=b+1;    
            }
        }
        c=0;
        for(i=0;i<5;i++){
            if(a[i][4-i]==0){
                c=c+1;    
            }
            else{
                break;
            }
        }
        if(c==5){
            b=b+1;
        }
        c=0;
        for(i=0;i<5;i++){
            if(a[i][i]==0){
                c=c+1;
            }
            else{
                break;
            }
        }
        if(c==5){
            b=b+1;
        }
        if(b>=3){
            printf("%d",k);
            return 0;
        }
    }
    return 0;
}