name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies using Homebrew
      run: |
        brew update
        brew install autoconf automake libtool pkg-config

    - name: Generate configure script
      run: autoreconf -i

    - name: Make configure executable
      run: chmod +x ./configure

    - name: Configure
      run: ./configure

    - name: Make
      run: make

    - name: Make Check
      run: make check

    - name: Make Distcheck
      run: make distcheck
